#Packages needed to be installed

install.packages("data.table")
library(data.table)
library(readr)
library(lubridate)
install.packages("ngram")
library(ngram)
library(e1071)
install.packages("Hmisc")
library(Hmisc)
install.packages("corrplot")
library(corrplot)
library(caret)
library(Metrics)
library(glmnet)
library(plotmo)
library(Rtsne)
library(ggplot2)
install.packages("stringr")
library(stringr)
library(xgboost)
library(tidytext)
library(dplyr)
install.packages("tm")
library(tm)
library(SnowballC)
library(stringr)